// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../imgConvert/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "convert:done": main$0.SummaryEvent;
            "convert:error": main$0.ErrorEvent;
            "convert:progress": main$0.ProgressEvent;
            "convert:result": main$0.ResultEvent;
            "files:added": main$0.FileItem[];
            "settings:changed": main$0.Settings;
            "window:maximise": boolean;
        }
    }
}
