//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../imgConvert/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "convert:done": $$createType0,
        "convert:error": $$createType1,
        "convert:progress": $$createType2,
        "convert:result": $$createType3,
        "files:added": $$createType5,
        "settings:changed": $$createType6,
    }));
}

// Private type creation functions
const $$createType0 = main$0.SummaryEvent.createFrom;
const $$createType1 = main$0.ErrorEvent.createFrom;
const $$createType2 = main$0.ProgressEvent.createFrom;
const $$createType3 = main$0.ResultEvent.createFrom;
const $$createType4 = main$0.FileItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = main$0.Settings.createFrom;

configure();
