// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 是主窗口与设置窗口共用的后端服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPaths 把文件/目录展开为列表项并追加到列表（内部去重）。
 * @param {string[]} paths
 * @returns {$CancellablePromise<$models.FileItem[]>}
 */
export function AddPaths(paths) {
    return $Call.ByID(2821272091, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Cancel 请求取消当前批次。
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(2235268088);
}

/**
 * ClearFiles 清空列表。
 * @returns {$CancellablePromise<void>}
 */
export function ClearFiles() {
    return $Call.ByID(3757529338);
}

/**
 * GetInfo 返回应用与引擎信息。
 * @returns {$CancellablePromise<$models.Info>}
 */
export function GetInfo() {
    return $Call.ByID(896949046).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSettings 返回当前高级设置。
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(3018893939).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * OpenPath 打开目录（不存在时尝试创建）。
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenPath(path) {
    return $Call.ByID(2898191345, path);
}

/**
 * RemoveFiles 按 ID 移除列表项。
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFiles(ids) {
    return $Call.ByID(1675677025, ids);
}

/**
 * SaveSettings 保存高级设置并广播给所有窗口。
 * @param {$models.Settings} st
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(st) {
    return $Call.ByID(3784651466, st);
}

/**
 * SelectFiles 弹出多选文件对话框，返回选中的绝对路径。
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectFiles() {
    return $Call.ByID(3693836357).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SelectFolder 弹出目录选择对话框。
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(4134204634);
}

/**
 * SelectOutputDir 弹出输出目录选择对话框。
 * @returns {$CancellablePromise<string>}
 */
export function SelectOutputDir() {
    return $Call.ByID(3713261170);
}

/**
 * ShowInFolder 在系统文件管理器中定位文件。
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function ShowInFolder(path) {
    return $Call.ByID(3005410256, path);
}

/**
 * Start 校验参数后异步开始转换。
 * @param {$models.ConvertConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function Start(cfg) {
    return $Call.ByID(2780549810, cfg);
}

/**
 * WindowClose 关闭主窗口。
 * @returns {$CancellablePromise<void>}
 */
export function WindowClose() {
    return $Call.ByID(233884162);
}

/**
 * WindowMinimise 最小化主窗口。
 * @returns {$CancellablePromise<void>}
 */
export function WindowMinimise() {
    return $Call.ByID(1381835851);
}

/**
 * WindowToggleMaximise 主窗口最大化/还原。
 * @returns {$CancellablePromise<void>}
 */
export function WindowToggleMaximise() {
    return $Call.ByID(1841899161);
}

// Private type creation functions
const $$createType0 = $models.FileItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Info.createFrom;
const $$createType3 = $models.Settings.createFrom;
const $$createType4 = $Create.Array($Create.Any);
