// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConvertConfig 前端“开始转换”时提交的参数。
 */
export class ConvertConfig {
    /**
     * Creates a new ConvertConfig instance.
     * @param {Partial<ConvertConfig>} [$$source = {}] - The source object to create the ConvertConfig.
     */
    constructor($$source = {}) {
        if (!("format" in $$source)) {
            /**
             * Format 输出格式名，单选；是否无损由各格式内置预设决定。
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quality"] = 0;
        }
        if (!("resizeMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resizeMode"] = "";
        }
        if (!("resizeValue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["resizeValue"] = 0;
        }
        if (!("overwrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overwrite"] = false;
        }
        if (!("workers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workers"] = 0;
        }
        if (!("outDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outDir"] = "";
        }
        if (!("writeLog" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["writeLog"] = false;
        }
        if (!("logPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConvertConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConvertConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConvertConfig(/** @type {Partial<ConvertConfig>} */($$parsedSource));
    }
}

/**
 * ErrorEvent 运行期错误提示，随 convert:error 事件下发。
 */
export class ErrorEvent {
    /**
     * Creates a new ErrorEvent instance.
     * @param {Partial<ErrorEvent>} [$$source = {}] - The source object to create the ErrorEvent.
     */
    constructor($$source = {}) {
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ErrorEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ErrorEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ErrorEvent(/** @type {Partial<ErrorEvent>} */($$parsedSource));
    }
}

/**
 * FileItem 列表中的一行（一个源文件）。
 */
export class FileItem {
    /**
     * Creates a new FileItem instance.
     * @param {Partial<FileItem>} [$$source = {}] - The source object to create the FileItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("base" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base"] = "";
        }
        if (!("rel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rel"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * pending / running / ok / skip / error / canceled
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("outSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outSize"] = 0;
        }
        if (!("ratio" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ratio"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("results" in $$source)) {
            /**
             * Results 转换结果（输出格式单选，最多一条）
             * @member
             * @type {ResultItem[]}
             */
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileItem}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField11_0($$parsedSource["results"]);
        }
        return new FileItem(/** @type {Partial<FileItem>} */($$parsedSource));
    }
}

/**
 * FormatInfo 供前端渲染格式选择项。
 */
export class FormatInfo {
    /**
     * Creates a new FormatInfo instance.
     * @param {Partial<FormatInfo>} [$$source = {}] - The source object to create the FormatInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }
        if (!("tip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tip"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormatInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FormatInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FormatInfo(/** @type {Partial<FormatInfo>} */($$parsedSource));
    }
}

/**
 * Info 应用启动信息。
 */
export class Info {
    /**
     * Creates a new Info instance.
     * @param {Partial<Info>} [$$source = {}] - The source object to create the Info.
     */
    constructor($$source = {}) {
        if (!("appVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appVersion"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("frameless" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["frameless"] = false;
        }
        if (!("cpus" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpus"] = 0;
        }
        if (!("vipsVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vipsVersion"] = "";
        }
        if (!("vipsPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vipsPath"] = "";
        }
        if (!("engineError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["engineError"] = "";
        }
        if (!("formats" in $$source)) {
            /**
             * @member
             * @type {FormatInfo[]}
             */
            this["formats"] = [];
        }
        if (!("inputExts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["inputExts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Info}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formats" in $$parsedSource) {
            $$parsedSource["formats"] = $$createField7_0($$parsedSource["formats"]);
        }
        if ("inputExts" in $$parsedSource) {
            $$parsedSource["inputExts"] = $$createField8_0($$parsedSource["inputExts"]);
        }
        return new Info(/** @type {Partial<Info>} */($$parsedSource));
    }
}

/**
 * ProgressEvent 整体进度，随 convert:progress 事件下发。
 */
export class ProgressEvent {
    /**
     * Creates a new ProgressEvent instance.
     * @param {Partial<ProgressEvent>} [$$source = {}] - The source object to create the ProgressEvent.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ok"] = 0;
        }
        if (!("skip" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skip"] = 0;
        }
        if (!("fail" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fail"] = 0;
        }
        if (!("elapsedMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProgressEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgressEvent(/** @type {Partial<ProgressEvent>} */($$parsedSource));
    }
}

/**
 * ResultEvent 单个 (文件, 格式) 组合的转换结果，随 convert:result 事件下发。
 */
export class ResultEvent {
    /**
     * Creates a new ResultEvent instance.
     * @param {Partial<ResultEvent>} [$$source = {}] - The source object to create the ResultEvent.
     */
    constructor($$source = {}) {
        if (!("jobId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jobId"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("outPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outPath"] = "";
        }
        if (!("inBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inBytes"] = 0;
        }
        if (!("outBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outBytes"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResultEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResultEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResultEvent(/** @type {Partial<ResultEvent>} */($$parsedSource));
    }
}

/**
 * ResultItem 单个格式的结果明细。
 */
export class ResultItem {
    /**
     * Creates a new ResultItem instance.
     * @param {Partial<ResultItem>} [$$source = {}] - The source object to create the ResultItem.
     */
    constructor($$source = {}) {
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("outPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outPath"] = "";
        }
        if (!("outSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outSize"] = 0;
        }
        if (!("ratio" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ratio"] = 0;
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResultItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResultItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResultItem(/** @type {Partial<ResultItem>} */($$parsedSource));
    }
}

/**
 * Settings 高级设置。
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("format" in $$source)) {
            /**
             * Format 输出格式名（avif/webp/jpeg/jxl/png），单选。
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * Quality 等效 JPEG 质量 1-100。
             * @member
             * @type {number}
             */
            this["quality"] = 0;
        }
        if (!("resizeMode" in $$source)) {
            /**
             * ResizeMode 输出尺寸模式："" 原尺寸 / "fw" 固定宽 / "fh" 固定高 /
             * "fl" 固定长边（均可放大缩小，等比缩放）/ "pct" 按百分比等比缩放。
             * @member
             * @type {string}
             */
            this["resizeMode"] = "";
        }
        if (!("resizeValue" in $$source)) {
            /**
             * ResizeValue 限制/固定边的像素值。
             * @member
             * @type {number}
             */
            this["resizeValue"] = 0;
        }
        if (!("overwrite" in $$source)) {
            /**
             * Overwrite 覆盖已存在的输出文件。
             * @member
             * @type {boolean}
             */
            this["overwrite"] = false;
        }
        if (!("workers" in $$source)) {
            /**
             * Workers 并发 vips 进程数，0 表示 CPU 核数。
             * @member
             * @type {number}
             */
            this["workers"] = 0;
        }
        if (!("outputMode" in $$source)) {
            /**
             * OutputMode "source" 输出到原目录；"custom" 输出到 CustomDir。
             * @member
             * @type {string}
             */
            this["outputMode"] = "";
        }
        if (!("customDir" in $$source)) {
            /**
             * CustomDir 自定义输出根目录。
             * @member
             * @type {string}
             */
            this["customDir"] = "";
        }
        if (!("writeLog" in $$source)) {
            /**
             * WriteLog 是否写入转换日志。
             * @member
             * @type {boolean}
             */
            this["writeLog"] = false;
        }
        if (!("logPath" in $$source)) {
            /**
             * LogPath 日志文件路径，空表示使用配置目录下的 convert.log。
             * @member
             * @type {string}
             */
            this["logPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * SummaryEvent 批次结束汇总，随 convert:done 事件下发。
 */
export class SummaryEvent {
    /**
     * Creates a new SummaryEvent instance.
     * @param {Partial<SummaryEvent>} [$$source = {}] - The source object to create the SummaryEvent.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ok"] = 0;
        }
        if (!("skip" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skip"] = 0;
        }
        if (!("fail" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fail"] = 0;
        }
        if (!("inBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inBytes"] = 0;
        }
        if (!("outBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outBytes"] = 0;
        }
        if (!("ratio" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ratio"] = 0;
        }
        if (!("elapsedMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["elapsedMs"] = 0;
        }
        if (!("canceled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canceled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SummaryEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SummaryEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SummaryEvent(/** @type {Partial<SummaryEvent>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ResultItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = FormatInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
